language: minimal

include:
  - os: linux
    dist: xenial
    sudo: true

script:
  - apt-get update -y
  - apt-get install -y sshpass
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - sshpass -p $CI_PASSWORD ssh -tt visitor_persh@vm.toliak.ru 'ssh -o "StrictHostKeyChecking no" -tt PershVM ./update-alice.sh'